### ISSUE TITLE
Feature Request: Block Promoted Tweets

### ISSUE THREAD

**Issue by BillLudwig** [kheina-com/Blue-Blocker#128] opened 2023-06-15 19:55 UTC
I manually block all of these I come across but it would be pretty spectacular if this could be done automatically.  Thanks!

**Comment by DanielleMiu** [comment] 2023-06-15 19:59
duplicate of https://github.com/kheina-com/Blue-Blocker/issues/5

**Closed by DanielleMiu** 2023-06-15 19:59 UTC
