### ISSUE TITLE
Searching and especially opening a populated qrt feed causes the following error to flood console + popup on webpage

### ISSUE THREAD

**Issue by VierraButFox** [kheina-com/Blue-Blocker#213] opened 2023-10-21 00:13 UTC
```
[Blue Blocker] found unexpected tweet shape: 
Object { entryType: "TimelineTimelineItem", __typename: "TimelineTimelineItem", itemContent: {…}, feedbackInfo: {…}, clientEventInfo: {…} }
chunk-af3d2282.js:1:11800
    V moz-extension://0de7d10f-446d-4874-9ccf-417ae0a2f851/assets/chunk-af3d2282.js:1
    we moz-extension://0de7d10f-446d-4874-9ccf-417ae0a2f851/assets/chunk-af3d2282.js:1
    <anonymous> moz-extension://0de7d10f-446d-4874-9ccf-417ae0a2f851/assets/chunk-af3d2282.js:1
```

**Comment by rougetimelord** [comment] 2023-11-29 19:53
Pretty sure this is a duplicate of #206

**Comment by cooljeanius** [comment] 2023-11-29 19:55
> Pretty sure this is a duplicate of #206

oh yeah it's got "unexpected tweet shape" in it; closing as a dup of #206

**Closed by cooljeanius** 2023-11-29 19:55 UTC
