### ISSUE TITLE
Stopped Queuing New Accounts to Block/Mute

### ISSUE THREAD

**Issue by maciakl** [kheina-com/Blue-Blocker#81] opened 2023-05-08 18:57 UTC
The extension stopped queuing new accounts to block today. It was still blocking accounts that were in the queue, but once it blocked them all, it now remains at 0 no matter what I do.

Scrolling through threads full of check marks does nothing. Visiting their profiles directly does nothing.

In the console I see a lot of warnings such as:

>The resource URL was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by DanielleMiu** [comment] 2023-05-08 19:36
first off, very weird, thanks for submitting. second of all, I believe the warning you're seeing is a twitter issue. that particular issue is caused by `<link ...>` nodes in the head with `rel="preload"` on them, but their actual values not being used. twitter is written like shit and just one of the many issues it has.

in the mean time, try closing all twitter tabs (tweetdeck, twitter.com, etc) and waiting 5 seconds before opening them back up. if it's an issue with the queue syncing between tabs, this should reset it. if you could provide more details on what you were doing at the time you saw this, it would help a lot. (how many twitter tabs did you have open, what version were you running, what page were you on when this occurred, any other detail you can think of.)

I see someone +1'd this, so if anyone else is experiencing this issue, if you could provide these details too it would help immensely with replicating the issue

**Comment by neonharbor** [comment] 2023-05-08 19:50
Having the exact same problem since this morning. It doesn't seem to matter how many tabs I have open, and I've also tried a private tab. I have tried closing and reopening the browser. I'm using Brave  v1.51.110 on Windows 11. Blue Blocker v0.2.4.

**Comment by neonharbor** [comment] 2023-05-08 20:36
Here it is! No sign of "authorization" so I should be good:

`{
    "BlockCounter": 172,
    "BlockCounterCriticalPoint": null,
    "BlockQueue": null,
    "BlockQueueCriticalPoint": null,
    "MultiTabEvent": {
        "headers": null,
        "reason": 0,
        "type": "UserBlockedEvent",
        "user": {
            "has_nft_avatar": false,
            "is_blue_verified": true,
            "legacy": {
                "blocking": false,
                "followed_by": false,
                "followers_count": 15771,
                "following": false,
                "name": "Sterling Crispin 🕊️",
                "screen_name": "sterlingcrispin",
                "verified": false
            },
            "rest_id": "65498425",
            "super_following": false
        },
        "user_id": "65498425"
    },
    "QueueConsumerCriticalPoint": null,
    "blockCounterCriticalPoint": null
}`

**Comment by DanielleMiu** [comment] 2023-05-08 20:46
you're safe there. though, all your critical points are null, so they shouldn't be blocking.

when you open twitter tabs there are no errors in the console? look for things like shared.js, block_queue.js, and queue_consumer.js. I'm also assuming when you open the context menu it says that 0 are queued. let me know if it's not 0

try going to this page to make sure that things are trying to be queued and let me know what shows up in the console (again, checking for `authorization`, just in case. it shouldn't show up here but you can't be too careful
https://twitter.com/search?q=-filter%3Averified%20filter%3Ablue_verified%20filter%3Areplies&src=recent_search_click&f=live

so sorry about going through all this, but I can't replicate your issue on my machine

**Comment by DanielleMiu** [comment] 2023-05-08 21:29
thanks @sonololo I Think your issue was the opposite (failing to consume queue vs failing to write to queue) but this is also good info. I've been meaning to read user objects in a safer way anyway, so I'll definitely add that in 0.2.5

**Comment by sonololo** [comment] 2023-05-08 21:35
To be honest something weird happened again, and this time I can't figure out the problem. The block count jumped to 868 and stopped again.

```
{
    "BlockCounter": 868,
    "BlockCounterCriticalPoint": null,
    "BlockQueue": null,
    "BlockQueueCriticalPoint": null,
    "MultiTabEvent": {
        "type": "UserBlockedEvent",
        "user": {
            "__typename": "User",
            "id": "VXNlcjoxMTM3MDMwNzA4NDQ1MjMzMTUy",
            "rest_id": "1137030708445233152",
            "affiliates_highlighted_label": {},
            "has_graduated_access": true,
            "is_blue_verified": true,
            "profile_image_shape": "Circle",
            "legacy": {
                "can_dm": true,
                "can_media_tag": true,
                "created_at": "Fri Jun 07 16:17:00 +0000 2019",
                "default_profile": true,
                "default_profile_image": false,
                "description": "",
                "entities": {
                    "description": {
                        "urls": []
                    },
                    "url": {}
                },
                "fast_followers_count": 0,
                "favourites_count": 100316,
                "followers_count": 6414,
                "friends_count": 2096,
                "has_custom_timelines": true,
                "is_translator": false,
                "listed_count": 56,
                "location": "",
                "media_count": 441,
                "name": "Blank Embrace",
                "normal_followers_count": 6414,
                "pinned_tweet_ids_str": [],
                "possibly_sensitive": false,
                "profile_banner_url": "",
                "profile_image_url_https": "",
                "profile_interstitial_type": "",
                "screen_name": "BlankEmbrace",
                "statuses_count": 31617,
                "translator_type": "none",
                "url": "",
                "verified": false,
                "want_retweets": false,
                "withheld_in_countries": []
            }
        },
        "user_id": "1137030708445233152",
        "headers": null,
        "reason": 0
    },
    "QueueConsumerCriticalPoint": null
}
```

Now nothing, including changing options randomly and restarting the browser makes it fill the queue, it's stuck at 0 again. Weird.

**Comment by DanielleMiu** [comment] 2023-05-08 21:47
this seems closer to the issue in this thread. I still don't know what's going on, try doing the steps from [this comment](https://github.com/kheina-com/Blue-Blocker/issues/81#issuecomment-1539027504) and letting me know what shows up in your console. you may need to scroll a little on that page since on initial pageload requests can be missed by the addon

**Comment by sonololo** [comment] 2023-05-08 21:47
OK, I have established it kinda now, managed to figure out:

* It succesfully queues users to block and blocks them if they appear in my feed. Looking at the "For You" timeline instantly queued 10 more users and blocked them.

* It does not queue users when I browse replies for tweets like these: https://twitter.com/elonmusk/status/1654972024203223041 - no queueing at all.

**Comment by DanielleMiu** [comment] 2023-05-08 21:59
@neonharbor please check [this comment](https://github.com/kheina-com/Blue-Blocker/issues/81#issuecomment-1539097666) and see if this is your issue as well. I will attempt to confirm myself asap

**Comment by DanielleMiu** [comment] 2023-05-08 22:00
a recent review on chrome seems to imply this is the issue also

> It's not really working. It'll occasionally block some people, but when I go on a popular tweet with a lot of blue replies, it doesn't block anyone.

**Comment by DanielleMiu** [comment] 2023-05-08 22:17
so checking this myself
working: For You, Following, search results
**not working**: tweet replies, User Pages(?), individual tweets(?)

(hard to those last two)

seems like they pushed an update to their api

**Comment by anarchothaumaturgist** [comment] 2023-05-08 22:51
> if anyone on this thread has some free time and wants to double check these that would be very helpful

Just chiming in to say I'm experiencing the exact same thing. Going into replies doesn't sweep anybody up, but it still seems to work elsewhere. Just started happening today. I ended up here trying to figure out what was going on.

**Comment by DanielleMiu** [comment] 2023-05-08 23:05
ok. I figured out the issue and the solution. it's very irritating. they changed the graphql used by these two endpoints. [twitter's] graphql works by compiling a query and saving it's id and invoking it via a url in the format `https://twitter.com/i/api/graphql/<query id>/<query name>` the query for TweetDetail (which serves individual tweets and tweet replies) was updated and the new query id (base64 encoded) contains a `-`. the magic regex used to check urls only allowed alphanumerics and periods. adding `-` (and `_` because url b64 encoding and also `=`, just to be safe) fixes this issue. I'll push an update asap, the new version will be `0.2.5`, all bugs and features already labelled `0.2.5` will be pushed to `0.2.6`

**Comment by neonharbor** [comment] 2023-05-08 23:11
Rad, thanks so much!!

**Closed** 2023-05-08 23:37 UTC
Labels: bug, important

**Comment by DanielleMiu** [comment] 2023-05-08 23:39
I've pushed the new version to both web stores. it could take a while for them to be approved, and even longer for your browser to automatically update. I'll keep this thread updated for when they are fully published so you can manually update, if you want

**Comment by DanielleMiu** [comment] 2023-05-08 23:41
firefox has been published and is live

**Comment by DanielleMiu** [comment] 2023-05-08 23:48
chrome has been published and is live

thanks for the help everyone, it was invaluable

**Comment by sonololo** [comment] 2023-05-08 23:54
Fully working now, thanks!

**Comment by neonharbor** [comment] 2023-05-09 02:16
> chrome has been published and is live
> 
> thanks for the help everyone, it was invaluable

No way buddy, your _plugin_ is invaluable!

**Comment by crispybegs** [comment] 2023-05-09 04:56
than you for your service.
i have v0.24 in chrome but it's still not working. the dev console is a string of stuff like this..

<img width="452" alt="Screenshot 2023-05-09 at 05 55 49" src="https://user-images.githubusercontent.com/129169122/236997704-b00c5b1e-d3cc-4980-b442-488ce54d05a3.png">

Any ideas?

**Comment by crispybegs** [comment] 2023-05-09 07:26
v0.25 seems to be working, thank you!
