### ISSUE TITLE
Console errors happening suddenly

### ISSUE THREAD

**Issue by joemsak** [kheina-com/Blue-Blocker#204] opened 2023-09-06 18:18 UTC
```
[Blue Blocker] unexpected error occurred while parsing request body 
Object { error: TypeError, body_str: '{"data":{"home":{}}}', event: blue-blocker-event }
​
body_str: '{"data":{"home":{}}}'
​
error: TypeError: s is undefined
​
event: blue-blocker-event { target: HTMLDocument https://twitter.com/home, isTrusted: false, detail: {…}, … }
​
<prototype>: Object { … }
chunk-af3d2282.js:1:16065

```

```
{
  "error": {},
  "body_str": "{\"data\":{\"home\":{}}}",
  "event": {
    "isTrusted": false
  }
}
```

Using Ubuntu 22, Firefox 117.0, BlueBlocker v0.3.4

**Comment by kheina** [comment] 2023-09-07 17:51
this is a duplicate of #184, it's not technically a blue blocker bug, but rather twitter being dumb as hell and sending an empty response

**Closed by kheina** 2023-09-07 17:51 UTC
