### ISSUE TITLE
An error has ocurred, check the console and open an issue on GitHub

### ISSUE THREAD

**Issue by Reonu** [kheina-com/Blue-Blocker#207] opened 2023-09-16 23:02 UTC
Your wish is my command :)

```NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFaviconService.replaceFaviconDataFromDataURL]
    loadFavicon resource:///modules/PlacesUIUtils.sys.mjs:213
    loadFavicon resource:///modules/PlacesUIUtils.sys.mjs:640
    setIconFromLink resource:///actors/LinkHandlerParent.sys.mjs:139
    receiveMessage resource:///actors/LinkHandlerParent.sys.mjs:60
LinkHandlerParent.sys.mjs:148:17
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFaviconService.replaceFaviconDataFromDataURL]
    loadFavicon resource:///modules/PlacesUIUtils.sys.mjs:213
    loadFavicon resource:///modules/PlacesUIUtils.sys.mjs:640
    setIconFromLink resource:///actors/LinkHandlerParent.sys.mjs:139
    receiveMessage resource:///actors/LinkHandlerParent.sys.mjs:60
LinkHandlerParent.sys.mjs:148:17
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFaviconService.replaceFaviconDataFromDataURL]
    loadFavicon resource:///modules/PlacesUIUtils.sys.mjs:213
    loadFavicon resource:///modules/PlacesUIUtils.sys.mjs:640
    setIconFromLink resource:///actors/LinkHandlerParent.sys.mjs:139
    receiveMessage resource:///actors/LinkHandlerParent.sys.mjs:60
LinkHandlerParent.sys.mjs:148:17
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFaviconService.replaceFaviconDataFromDataURL]
    loadFavicon resource:///modules/PlacesUIUtils.sys.mjs:213
    loadFavicon resource:///modules/PlacesUIUtils.sys.mjs:640
    setIconFromLink resource:///actors/LinkHandlerParent.sys.mjs:139
    receiveMessage resource:///actors/LinkHandlerParent.sys.mjs:60
LinkHandlerParent.sys.mjs:148:17
Política de referentes: Ignorando la política de referencias menos restringida “unsafe-url” para la solicitud de sitios cruzados: https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&expflag=embeds_enable_muted_autoplay%3Atrue&fs=1 embed
this.window.gBrowserInit is undefined 2 ext-browser.js:1134
```

I was browsing a search result when it happened. I'd rather not share the exact search prompt but the format of the search was `from:account word`. I can't reproduce it with the same prompt though.

**Comment by dranthir** [comment] 2023-09-27 07:51
same issue when opening a profile page on Twitter/X

**Comment by jl1989-2** [comment] 2023-12-03 05:11
This is happening to me as well. It's getting extremely annoying because I'll sometimes have 20+ of these prompts show up at once.

**Comment by cooljeanius** [comment] 2023-12-06 17:15
did it say anything about an unexpected tweet shape? If so, it might be a dup of that other bug about unexpected tweet shapes...

**Comment by rougetimelord** [comment] 2024-04-09 19:38
I don't think there's enough info here to diagnose, and I haven't been able to reproduce. Closing for now.

**Closed by rougetimelord** 2024-04-09 19:38 UTC
