### ISSUE TITLE
Hide posts from queued accounts

### ISSUE THREAD

**Issue by kolgza** [kheina-com/Blue-Blocker#201] opened 2023-08-26 18:38 UTC
Currently, the user must wait for the queue to finish before not seeing posts from queued accounts. [BlueLiteBlocker](https://github.com/BlueLiteBlocker/BlueLiteBlocker/tree/master) solves this by simply hiding all posts from Twitter Blue users, although it does not block accounts.

**Comment by kheina** [comment] 2023-09-04 01:57
closing as it's a duplicate of #17, but I would recommend simply running both extensions for now. I doubt I'll add this as a feature and blue blocker and blueliteblocker shouldn't interfere with each other

**Closed by kheina** 2023-09-04 01:57 UTC
