### ISSUE TITLE
Logged out when blocking too many accounts

### ISSUE THREAD

**Issue by konomikitten** [kheina-com/Blue-Blocker#18] opened 2023-04-26 02:41 UTC
Is there anyway this problem can be mitigated? I don't mind just logging back in again but a lot of users will probably find this off putting. I know the extension already has a queue system, so maybe it can be improved to reduce the likely hood that Twitter will log you out.

**Comment by konomikitten** [comment] 2023-04-26 09:01
This (https://twitter.com/elonmusk/status/1650731557164818437) is a good thread to see how Twitter will forcibly log you out if you block too many people at once. I've been logged out at least twice letting Blue Blocker 0.2 run in this thread.

**Comment by KDederichs** [comment] 2023-04-26 16:07
It's rate limited if I had to guess.
Once the PR with local storage is merged it'd probably good to just increase the queue interval to 10 or 15 seconds (or more) and let that work in the background. That probably should solve it.

**Comment by DanielleMiu** [comment] 2023-04-26 16:58
I don't think a flat increase in queue interval is the best idea. I'm more interested in something like a backoff, where it starts out at a low interval like 1s, but after 5 or 10 requests in quick succession, it's increased to 5 or 10s automatically

**Comment by DanielleMiu** [comment] 2023-04-29 22:44
so I confirmed that this is actually an issue with the internal queue. However, I'm not sure how much of an issue it actually is, since the only way I could trigger is was by rapidly scrolling on the "For You" page. Likely more due to hitting the new tweets endpoints multiple times within 2-3 seconds rather than a single block occurring every 5 seconds.

**Comment by KDederichs** [comment] 2023-04-29 22:57
You also run into this when you just block a lot of them manually (had that happen).
There probably is some sort of limit on it, where you can only block X of them in a given time frame before it kicks you off.
Sadly they don't set Rate limit headers so you can't really figure it out except through testing what the limit is and when it resets (pretty sure 1h is the maximum amount it takes though)

**Closed** 2023-05-01 04:30 UTC
Labels: bug, enhancement
